/** Re-exports shared operator-console API types and review helpers. */
export {
  isClaimKeyAliasConvergenceProposal,
  isManualProposalSettlementEligible,
  isSingleDurableClaimKeyRepairProposal,
  type ManualProposalSettlementChoice,
} from "../../../src/web-api/proposal-review.js";
export type {
  ApiErrorBody,
  CockpitSnapshot,
  DreamJobEvent,
  DreamJobSnapshot,
  DreamJobStatus,
  DreamProposal,
  DreamRunActionView,
  DreamRunRecord,
  DreamRunStatus,
  DreamRunsResponse,
  Durable,
  DurableKind,
  DurableListResult,
  DurableTrace,
  Episode,
  EpisodeListResult,
  Expiry,
  GitWorktreeStatus,
  HealthStats,
  InstanceView,
  InstancesResponse,
  MemoryFacets,
  Procedure,
  ProcedureDocument,
  ProcedureSaveResult,
  ProcedureSyncExecutionTotals,
  ProcedureSyncPlan,
  ProcedureValidation,
  ProcedureWorkspace,
  ProposalBacklogItem,
  ProposalDetail,
  SelectedInstanceResponse,
  StoreDurableBody,
  UpdateDurableMetadataBody,
  UpdateEpisodeMetadataBody,
} from "../../../src/web-api/types.js";
