import type { DreamRunAction } from "../../core/dreaming/domain/action-types.js";
import type { DreamTier } from "../../core/dreaming/types.js";
import type { DreamCompletionSummary, DreamProposalReviewStatus, DreamRunProposal, DreamRunStatus } from "../../core/dreaming/types.js";
import type { LlmPort } from "../../core/ports.js";
import type { Durable, DurableUpdateInput } from "../../core/types.js";

/** Token and cost accounting emitted by the cost-metered LLM wrappers used by dreaming. */
export interface DreamLlmUsageMetadata {
  inputTokens?: number;
  outputTokens?: number;
  totalCost?: number;
}

/** LLM port augmented with the cost-accounting metadata dreaming stages read to enforce budgets. */
export type CostMeteredLlm = LlmPort & {
  metadata?: { usage?: DreamLlmUsageMetadata };
};

/**
 * Narrative evidence row surfaced to the extract stage from one episode.
 */
export interface DreamEpisodeEvidence {
  id: string;
  summary: string;
  startedAt: string;
  endedAt: string | null;
  sessionId: string | null;
  project: string | null;
}

/**
 * Persisted dreaming run metadata returned by history and status queries.
 */
export interface DreamRunRecord {
  id: string;
  tier: DreamTier;
  project: string | null;
  startedAt: string;
  completedAt: string | null;
  status: DreamRunStatus;
  inputTokens: number;
  outputTokens: number;
  estimatedCostUsd: number;
  model: string | null;
  actionsTaken: number;
  actionsSkipped: number;
  durablesStaled: number;
  summaryJson: DreamCompletionSummary | null;
  error: string | null;
  dryRun: boolean;
  config: Record<string, unknown> | null;
}

/**
 * Persisted profile snapshot generated by the dreaming project stage.
 */
export interface DreamProfileSnapshot {
  id: string;
  durableIds: string[];
  directiveIds: string[];
  asOf: string;
  contentHash: string;
  runId: string | null;
  createdAt: string;
}

/**
 * Aggregate corpus health summary used by dreaming status tools.
 */
export interface DreamHealthStats {
  total: number;
  byType: Record<string, number>;
  claimKeyLifecycle: {
    trusted: number;
    tentative: number;
    unresolved: number;
    noKey: number;
  };
  /** Count of durable unresolved dreaming proposals awaiting review. */
  proposalBacklogCount: number;
  /** Open proposals that are already safe to apply. */
  eligibleProposalBacklogCount: number;
  /** Oldest still-open proposal creation timestamp, when one exists. */
  oldestOpenProposalCreatedAt: string | null;
  recency: {
    last7: number;
    last30: number;
    d30To90: number;
    d90Plus: number;
  };
  recall: {
    never: number;
    oneToFive: number;
    fivePlus: number;
  };
  quality: {
    high: number;
    medium: number;
    low: number;
    average: number;
  };
}

/**
 * Query options for the global proposal backlog view.
 */
export interface DreamProposalBacklogQuery {
  state?: DreamProposalReviewStatus | "all";
  issueKind?: string;
  eligibleOnly?: boolean;
  durableId?: string;
  limit?: number;
  offset?: number;
}

/**
 * Global backlog row that joins one proposal to its originating run metadata.
 */
export interface DreamProposalBacklogItem {
  proposal: DreamRunProposal;
  runPassType: DreamTier;
  runStartedAt: string;
  runStatus: DreamRunStatus;
  runDryRun: boolean;
}

/**
 * Milestone 1 dreaming persistence boundary.
 */
export interface DreamPort {
  getDailyCost(now?: Date): Promise<number>;
  createRun(run: {
    tier: DreamTier;
    project?: string;
    model?: string | null;
    dryRun: boolean;
    config?: Record<string, unknown> | null;
    startedAt?: string;
  }): Promise<string>;
  completeRun(
    runId: string,
    result: {
      status: DreamRunStatus;
      inputTokens: number;
      outputTokens: number;
      estimatedCostUsd: number;
      actionsTaken: number;
      actionsSkipped: number;
      durablesStaled: number;
      summaryJson?: DreamCompletionSummary | null;
      error?: string | null;
      completedAt?: string;
    },
  ): Promise<void>;
  logRunAction(action: DreamRunAction): Promise<void>;
  getLastRun(): Promise<DreamRunRecord | null>;
  getRunHistory(limit?: number): Promise<DreamRunRecord[]>;
  /** Returns the most recent applied (non-dry-run) `light` runs, newest first. */
  getRecentAppliedLightRuns(limit: number): Promise<DreamRunRecord[]>;
  getRunActions(runId: string): Promise<DreamRunAction[]>;
  getRunProposals(runId: string): Promise<DreamRunProposal[]>;
  getProposal(proposalId: string): Promise<DreamRunProposal | null>;
  reviewProposal(input: {
    proposalId: string;
    status: Exclude<DreamProposalReviewStatus, "open">;
    reason: string;
    reviewedAt?: string;
    appliedActionCount?: number;
  }): Promise<boolean>;
  listProposalBacklog(query?: DreamProposalBacklogQuery): Promise<DreamProposalBacklogItem[]>;
  getHealthStats(now?: Date): Promise<DreamHealthStats>;
  getDurable(durableId: string): Promise<Durable | null>;
  getDurables(durableIds: string[]): Promise<Durable[]>;
  closeDurableValidity(durableId: string, reason?: string): Promise<boolean>;
  updateDurable(
    durableId: string,
    fields: DurableUpdateInput,
    options?: {
      includeInactive?: boolean;
    },
  ): Promise<boolean>;
  listReconcileDurables(query: {
    project?: string;
    type?: string;
    claimKeyPrefix?: string;
    durableIds?: string[];
    includeInactive?: boolean;
  }): Promise<Durable[]>;
  /** Reads recent episode narrative evidence newer than one timestamp. */
  listEpisodeEvidenceSince(since: string, options?: { project?: string; limit?: number }): Promise<DreamEpisodeEvidence[]>;
  /** Lists live host-store durables written during one episode session window. */
  listSessionHostStoreDurables(sessionId: string, startedAt: string, endedAt: string): Promise<Durable[]>;
  /** Loads active durables that share one canonical claim key (context-lookup). */
  findActiveDurablesByClaimKey(claimKey: string): Promise<Durable[]>;
  /** Returns the subset of normalized content hashes that already exist among active durables. */
  findExistingNormContentHashes(hashes: string[]): Promise<Set<string>>;
  /** Inserts one new durable row written by the extract or temporalize stages. */
  insertDurable(durable: Durable, embedding: number[], contentHash: string): Promise<string>;
  /** Links one active durable to the newer durable that supersedes it. */
  supersedeDurable(oldDurableId: string, newDurableId: string, kind?: string, reason?: string): Promise<boolean>;
  logRunProposal(proposal: DreamRunProposal): Promise<void>;
  countEpisodesSince(since: string, project?: string): Promise<number>;
  countIngestFilesSince(since: string): Promise<number>;
  countDurablesCreatedSince(since: string, project?: string): Promise<number>;
  sumDurableImportanceCreatedSince(since: string, project?: string): Promise<number>;
  createProfileSnapshot(snapshot: DreamProfileSnapshot): Promise<void>;
  getActiveProfileSnapshot(): Promise<DreamProfileSnapshot | null>;
  updateDreamState(input: {
    lastSuccessfulRunAt?: string;
    unsynthesizedImportanceSum?: number;
    activeProfileSnapshotId?: string;
    updatedAt: string;
  }): Promise<void>;
  /** Attempts to acquire the singleton dreaming run lock row. */
  tryAcquireRunLock(holderToken: string): Promise<boolean>;
  /** Refreshes the dreaming run lock heartbeat when the holder token still matches. */
  heartbeatRunLock(holderToken: string): Promise<boolean>;
  /** Releases the dreaming run lock when the holder token still matches. */
  releaseRunLock(holderToken: string): Promise<void>;
  /**
   * Runs a callback inside a single write transaction so a group of related
   * dreaming writes either all commit or all roll back. The callback receives a
   * port bound to the transaction; nested executors fall back to running inline.
   */
  withTransaction<T>(fn: (tx: DreamPort) => Promise<T>): Promise<T>;
}
